name: Run Notebook Plot
on:  
  push:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0-21/3 * * *'
  workflow_dispatch:
jobs:
  build:
    name: Run Notebook for Deep learning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Crete Python Script from Jupyter via nbconvert
        run: |
          cd Notebooks/
          jupyter nbconvert --output-dir='./' --to script 833003241_DL_assign1.ipynb
      - name: Run script
        run: |
          python 833003241_DL_assign1.py

